import { useCallback, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useAuth } from '@/context/AuthContext';
import { apiGet, apiPatch } from '@/api/client';
import type { AuthUser } from '@/auth/authService';
import {
  bioProfileFromAuthUsers,
  isLikelyAutoGeneratedBio,
  resolveDisplayBio,
} from '@/utils/bioTemplate';

function displayBioForUser(
  u: AuthUser | null | undefined,
  sessionUser?: AuthUser | null
): string {
  const profile = bioProfileFromAuthUsers(u ?? undefined, sessionUser ?? undefined);
  return resolveDisplayBio(u?.bio, profile);
}

export default function ProfilePage() {
  const { token, user, updateSession, isDemoUser } = useAuth();
  const [bio, setBio] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [savedFlash, setSavedFlash] = useState(false);

  const applyUserBio = useCallback(
    async (u: AuthUser) => {
      const display = displayBioForUser(u, user);
      setBio(display);

      const stored = (u.bio ?? '').trim();
      if (
        !isDemoUser &&
        token &&
        display !== stored &&
        isLikelyAutoGeneratedBio(stored)
      ) {
        try {
          const res = await apiPatch('/profile', { bio: display });
          const data = (await res.json()) as {
            error?: string;
            token?: string;
            user?: AuthUser;
          };
          if (res.ok && data.token && data.user) {
            await updateSession({ token: data.token, user: data.user });
          }
        } catch {
          /* non-fatal: textarea still shows correct template */
        }
      }
    },
    [token, isDemoUser, updateSession, user]
  );

  const loadMe = useCallback(async () => {
    if (!token || isDemoUser) {
      const u = user;
      if (u) await applyUserBio(u);
      else setBio(displayBioForUser(undefined, user));
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await apiGet('/profile');
      const data = (await res.json()) as { user?: AuthUser };
      if (!res.ok) throw new Error((data as { error?: string }).error || 'Failed to load profile');
      const u = data.user;
      if (u) await applyUserBio(u);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  }, [token, isDemoUser, user, applyUserBio]);

  useEffect(() => {
    void loadMe();
  }, [loadMe]);

  const save = async () => {
    if (!token || isDemoUser) {
      setError('Sign in to save your profile.');
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const res = await apiPatch('/profile', { bio: bio.trim() });
      const data = (await res.json()) as { error?: string; token?: string; user?: AuthUser };
      if (!res.ok) throw new Error(data.error || 'Save failed');
      const { token: newToken, user: newUser } = data;
      if (newToken && newUser) {
        await updateSession({ token: newToken, user: newUser });
      }
      setSavedFlash(true);
      setTimeout(() => setSavedFlash(false), 2000);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Save failed');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="flex-1 min-h-0 flex flex-col page-with-header overflow-hidden">
      <div className="flex-1 min-h-0 overflow-y-auto px-[var(--page-padding-x)] pb-24 max-w-md mx-auto w-full">
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-2xl font-bold text-foreground mb-1">Profile</h1>
          <p className="text-sm text-muted-foreground mb-6">
            Your bio is shown when others view your profile from Discover.
          </p>

          {loading ? (
            <div className="flex justify-center py-12">
              <Loader2 className="animate-spin text-primary w-8 h-8" />
            </div>
          ) : (
            <>
              {error && <p className="text-sm text-destructive mb-4">{error}</p>}

              <div className="space-y-4">
                <div>
                  <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Bio
                  </label>
                  <Textarea
                    className="mt-2 min-h-[160px] text-sm"
                    placeholder="Tell nearby professionals about yourself…"
                    value={bio}
                    onChange={(e) => setBio(e.target.value)}
                  />
                </div>

                <Button className="w-full" onClick={() => void save()} disabled={saving}>
                  {saving ? (
                    <>
                      <Loader2 className="animate-spin mr-2 w-4 h-4" />
                      Saving…
                    </>
                  ) : savedFlash ? (
                    'Saved'
                  ) : (
                    'Save'
                  )}
                </Button>
              </div>
            </>
          )}
        </motion.div>
      </div>
    </div>
  );
}
