/**
 * User and profile persistence in Neon.
 * Handles: upsert user, profile, and durable profile fields.
 *
 * MIGRATION NEEDED — run in NeonDB before deploying:
 * ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio TEXT;
 * ALTER TABLE profiles ADD COLUMN IF NOT EXISTS graduation_year TEXT;
 * (See server/migrations/008_graduation_year.sql)
 */
const db = require('./db');
const {
  resolveDisplayBio,
  bioProfileFromRow,
  isLikelyAutoGeneratedBio,
  generateBio,
} = require('../utils/bioTemplate');

async function upsertUser(linkedinSubjectId, email) {
  const res = await db.query(
    `INSERT INTO users (linkedin_subject_id, email, updated_at)
     VALUES ($1, $2, NOW())
     ON CONFLICT (linkedin_subject_id)
     DO UPDATE SET email = EXCLUDED.email, updated_at = NOW()
     RETURNING id, linkedin_subject_id, email, created_at, updated_at`,
    [linkedinSubjectId, email || null]
  );
  return res.rows[0];
}

async function upsertProfile(userId, data) {
  const {
    fullName,
    firstName,
    lastName,
    headline,
    photoUrl,
    linkedinUrl,
  } = data;

  const res = await db.query(
    `INSERT INTO profiles (user_id, full_name, first_name, last_name, headline, photo_url, linkedin_url, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
     ON CONFLICT (user_id)
     DO UPDATE SET
       full_name = COALESCE(EXCLUDED.full_name, profiles.full_name),
       first_name = COALESCE(EXCLUDED.first_name, profiles.first_name),
       last_name = COALESCE(EXCLUDED.last_name, profiles.last_name),
       headline = COALESCE(EXCLUDED.headline, profiles.headline),
       photo_url = COALESCE(EXCLUDED.photo_url, profiles.photo_url),
       linkedin_url = COALESCE(NULLIF(EXCLUDED.linkedin_url, ''), profiles.linkedin_url),
       updated_at = NOW()
     RETURNING *`,
    [
      userId,
      fullName || null,
      firstName || null,
      lastName || null,
      headline || null,
      photoUrl || null,
      linkedinUrl || null,
    ]
  );
  return res.rows[0];
}

async function getProfileByLinkedInId(linkedinSubjectId) {
  const res = await db.query(
    `SELECT p.*, u.linkedin_subject_id, u.email
     FROM profiles p
     JOIN users u ON u.id = p.user_id
     WHERE u.linkedin_subject_id = $1`,
    [linkedinSubjectId]
  );
  return res.rows[0] || null;
}

async function getProfilesByUserIds(linkedinSubjectIds) {
  if (!linkedinSubjectIds || linkedinSubjectIds.length === 0) return [];
  const placeholders = linkedinSubjectIds.map((_, i) => `$${i + 1}`).join(',');
  const res = await db.query(
    `SELECT u.linkedin_subject_id, u.id AS user_uuid, p.user_id, p.full_name, p.first_name, p.last_name,
            p.headline, p.photo_url, p.linkedin_url, p.interests, p.bio, p.career,
            p.current_job_title, p.current_company, p.alma_mater, p.past_companies, p.graduation_year
     FROM profiles p
     JOIN users u ON u.id = p.user_id
     WHERE u.linkedin_subject_id IN (${placeholders})`,
    linkedinSubjectIds
  );
  return res.rows;
}

async function updateLinkedInUrl(linkedinSubjectId, linkedinUrl) {
  const res = await db.query(
    `UPDATE profiles p
     SET linkedin_url = $2, updated_at = NOW()
     FROM users u
     WHERE u.id = p.user_id AND u.linkedin_subject_id = $1
     RETURNING p.*`,
    [linkedinSubjectId, linkedinUrl]
  );
  return res.rows[0] || null;
}

async function updateInterests(linkedinSubjectId, interests) {
  const res = await db.query(
    `UPDATE profiles p
     SET interests = $2, updated_at = NOW()
     FROM users u
     WHERE u.id = p.user_id AND u.linkedin_subject_id = $1
     RETURNING p.*`,
    [linkedinSubjectId, Array.isArray(interests) ? interests : []]
  );
  return res.rows[0] || null;
}

async function updateProfessionalBackground(linkedinSubjectId, data) {
  const { currentJobTitle, currentCompany, almaMater, pastCompanies, graduationYear } = data;
  const existingRow = await getProfileByLinkedInId(linkedinSubjectId);
  const res = await db.query(
    `UPDATE profiles p
     SET current_job_title = $2,
         current_company = $3,
         alma_mater = $4,
         past_companies = $5,
         graduation_year = $6,
         updated_at = NOW()
     FROM users u
     WHERE u.id = p.user_id AND u.linkedin_subject_id = $1
     RETURNING p.*`,
    [
      linkedinSubjectId,
      currentJobTitle || null,
      currentCompany || null,
      almaMater || null,
      Array.isArray(pastCompanies) ? pastCompanies : [],
      graduationYear != null && String(graduationYear).trim() !== '' ? String(graduationYear).trim() : null,
    ]
  );
  const row = res.rows[0] || null;
  if (!row) return null;

  const storedBio =
    existingRow?.bio != null && String(existingRow.bio).trim() !== ''
      ? String(existingRow.bio).trim()
      : '';
  const profileInput = bioProfileFromRow(row, {
    currentJobTitle: data.currentJobTitle,
    currentCompany: data.currentCompany,
    almaMater: data.almaMater,
    graduationYear: data.graduationYear,
    pastCompanies: data.pastCompanies,
  });
  const newBio = generateBio(profileInput);
  if (!storedBio || isLikelyAutoGeneratedBio(storedBio)) {
    await db.query(
      `UPDATE profiles p
       SET bio = $2, updated_at = NOW()
       FROM users u
       WHERE u.id = p.user_id AND u.linkedin_subject_id = $1`,
      [linkedinSubjectId, newBio]
    );
    row.bio = newBio;
  }

  return row;
}

async function updateGoals(linkedinSubjectId, goals) {
  const res = await db.query(
    `UPDATE profiles p
     SET goals = $2, updated_at = NOW()
     FROM users u
     WHERE u.id = p.user_id AND u.linkedin_subject_id = $1
     RETURNING p.*`,
    [linkedinSubjectId, Array.isArray(goals) ? goals : []]
  );
  return res.rows[0] || null;
}

/** Merge JWT user payload with durable Neon profile fields (for /auth/me). */
function mergeJwtUserWithProfileRow(baseUser, row) {
  const merged = row
    ? {
        ...baseUser,
        name: row.full_name || baseUser.name,
        headline: row.headline || baseUser.headline,
        picture: row.photo_url || baseUser.picture,
        linkedinUrl: row.linkedin_url ?? baseUser.linkedinUrl ?? '',
        currentJobTitle: row.current_job_title ?? baseUser.currentJobTitle,
        currentCompany: row.current_company ?? baseUser.currentCompany,
        almaMater:
          row.alma_mater != null && String(row.alma_mater).trim() !== ''
            ? String(row.alma_mater).trim()
            : baseUser.almaMater != null && String(baseUser.almaMater).trim() !== ''
              ? String(baseUser.almaMater).trim()
              : '',
        pastCompanies: Array.isArray(row.past_companies) ? row.past_companies : baseUser.pastCompanies ?? [],
        graduationYear:
          row.graduation_year != null && String(row.graduation_year).trim() !== ''
            ? String(row.graduation_year).trim()
            : baseUser.graduationYear != null && String(baseUser.graduationYear).trim() !== ''
              ? String(baseUser.graduationYear).trim()
              : '',
        bio: resolveDisplayBio(
          row.bio != null && String(row.bio).trim() !== ''
            ? String(row.bio).trim()
            : baseUser.bio ?? '',
          bioProfileFromRow(row, baseUser)
        ),
        career:
          row.career != null && String(row.career).trim() !== ''
            ? String(row.career).trim()
            : baseUser.career ?? '',
        isDiscoverable: row.is_discoverable === true,
      }
    : { ...baseUser };
  delete merged.interests;
  delete merged.goals;
  return merged;
}

async function getMergedUserForAuth(linkedinSubjectId, jwtUser) {
  const row = await getProfileByLinkedInId(linkedinSubjectId);
  return mergeJwtUserWithProfileRow(jwtUser, row);
}

/** Bio for API/sharing: template from background fields, unless user customized bio text. */
function bioForProfileRow(row) {
  if (!row) return '';
  const stored =
    row.bio != null && String(row.bio).trim() !== '' ? String(row.bio).trim() : '';
  return resolveDisplayBio(stored, bioProfileFromRow(row, {}));
}

const MAX_BIO_LENGTH = 800;

/**
 * PATCH fields: bio, career, interests (partial). interests uses same rules as PUT /profile/interests.
 */
async function updateProfileMePatch(linkedinSubjectId, patch) {
  const { bio, career, interests } = patch;
  const fields = [];
  const vals = [];
  let n = 1;

  if (bio !== undefined) {
    const b = String(bio ?? '');
    if (b.length > MAX_BIO_LENGTH) {
      const err = new Error('bio_too_long');
      err.code = 'bio_too_long';
      throw err;
    }
    fields.push(`bio = $${n++}`);
    vals.push(b || null);
  }
  if (career !== undefined) {
    fields.push(`career = $${n++}`);
    vals.push(String(career ?? '').trim() || null);
  }
  if (interests !== undefined) {
    fields.push(`interests = $${n++}`);
    vals.push(Array.isArray(interests) ? interests : []);
  }

  if (fields.length === 0) return getProfileByLinkedInId(linkedinSubjectId);

  vals.push(linkedinSubjectId);
  await db.query(
    `UPDATE profiles p
     SET ${fields.join(', ')}, updated_at = NOW()
     FROM users u
     WHERE u.id = p.user_id AND u.linkedin_subject_id = $${n}`,
    vals
  );
  return getProfileByLinkedInId(linkedinSubjectId);
}

async function updateIsDiscoverable(linkedinSubjectId, isDiscoverable) {
  await db.query(
    `UPDATE profiles p
     SET is_discoverable = $2, updated_at = NOW()
     FROM users u
     WHERE u.id = p.user_id AND u.linkedin_subject_id = $1`,
    [linkedinSubjectId, !!isDiscoverable]
  );
}
  const res = await db.query(
    `SELECT sp.id, sp.target_linkedin_subject_id, sp.created_at,
            p.full_name, p.headline, p.photo_url, p.linkedin_url, p.bio, p.career
     FROM saved_profiles sp
     JOIN users u ON u.linkedin_subject_id = sp.target_linkedin_subject_id
     JOIN profiles p ON p.user_id = u.id
     WHERE sp.saver_linkedin_subject_id = $1
     ORDER BY sp.created_at DESC`,
    [saverLinkedinSubjectId]
  );
  return res.rows;
}

async function insertSavedProfile(saverLinkedinSubjectId, targetLinkedinSubjectId) {
  if (saverLinkedinSubjectId === targetLinkedinSubjectId) {
    const err = new Error('cannot_save_self');
    err.code = 'cannot_save_self';
    throw err;
  }
  const res = await db.query(
    `INSERT INTO saved_profiles (saver_linkedin_subject_id, target_linkedin_subject_id)
     VALUES ($1, $2)
     ON CONFLICT (saver_linkedin_subject_id, target_linkedin_subject_id) DO NOTHING
     RETURNING id, created_at`,
    [saverLinkedinSubjectId, targetLinkedinSubjectId]
  );
  return { row: res.rows[0] || null, inserted: !!res.rows[0] };
}

async function deleteSavedProfile(saverLinkedinSubjectId, targetLinkedinSubjectId) {
  await db.query(
    `DELETE FROM saved_profiles
     WHERE saver_linkedin_subject_id = $1 AND target_linkedin_subject_id = $2`,
    [saverLinkedinSubjectId, targetLinkedinSubjectId]
  );
}

module.exports = {
  upsertUser,
  upsertProfile,
  getProfileByLinkedInId,
  getProfilesByUserIds,
  updateLinkedInUrl,
  updateInterests,
  updateProfessionalBackground,
  updateGoals,
  mergeJwtUserWithProfileRow,
  getMergedUserForAuth,
  bioForProfileRow,
  updateProfileMePatch,
  updateIsDiscoverable,
  listSavedProfilesForSaver,
  insertSavedProfile,
  deleteSavedProfile,
};
