/**
 * Profile bio template (mirrors src/utils/bioTemplate.ts).
 */

function coalesceNonEmpty(...values) {
  for (const v of values) {
    if (v == null) continue;
    const t = String(v).trim();
    if (t) return t;
  }
  return undefined;
}

function parsePastCompany(raw) {
  const t = String(raw ?? '').trim();
  const idx = t.toLowerCase().indexOf(' at ');
  if (idx > 0) {
    return { title: t.slice(0, idx).trim(), company: t.slice(idx + 4).trim() };
  }
  if (t) return { title: '', company: t };
  return { title: '', company: '' };
}

function firstMeaningfulWord(phrase) {
  const words = String(phrase).trim().split(/\s+/).filter(Boolean);
  let i = 0;
  while (i < words.length && /^(a|an|the)$/i.test(words[i])) i += 1;
  return words[i] || '';
}

function indefiniteArticle(followingPhrase) {
  const word = firstMeaningfulWord(followingPhrase);
  if (!word) return 'a';
  const lower = word.toLowerCase().replace(/^[\d\W]+/, '');
  if (!lower.length) return 'a';
  if (/^(hour|honest|honor|heir)\b/.test(lower)) return 'an';
  if (/^eu\b/.test(lower)) return 'a';
  if (/^one\b/.test(lower)) return 'a';
  if (/^(incoming|undergraduate|undergrad)\b/.test(lower)) return 'an';
  if (/^m\.?b\.?a\.?$/i.test(word)) return 'an';
  if (/^l\.?l\.?m\.?$/i.test(word)) return 'an';
  const first = lower[0];
  if ('aeiou'.includes(first)) {
    if (first === 'u' && /^(uni|user|usual|unicorn|use(?!d\b))\b/.test(lower)) return 'a';
    return 'an';
  }
  return 'a';
}

function parseGradYear(y) {
  if (y == null || y === '') return null;
  if (typeof y === 'number' && Number.isFinite(y)) {
    const n = Math.trunc(y);
    return n >= 1950 && n <= 2100 ? n : null;
  }
  const t = String(y).trim();
  if (/^\d{4}$/.test(t)) {
    const n = parseInt(t, 10);
    return Number.isFinite(n) ? n : null;
  }
  const m = t.match(/\b(19\d{2}|20\d{2}|2100)\b/);
  if (m) {
    const n = parseInt(m[1], 10);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function normalizeGraduationYear(y) {
  const n = parseGradYear(y);
  return n != null ? String(n) : undefined;
}

function educationLine(almaMater, graduationYear) {
  const school = String(almaMater ?? '').trim();
  if (!school) return null;
  const yearNum = parseGradYear(graduationYear);
  if (yearNum === null) return null;
  const y = String(yearNum);
  const currentYear = new Date().getFullYear();
  if (yearNum < currentYear) {
    return `I studied at ${school} and graduated in ${y}.`;
  }
  return `I am studying at ${school} and will graduate in ${y}.`;
}

function isCurrentStudentByGradYear(graduationYear) {
  const n = parseGradYear(graduationYear);
  if (n === null) return false;
  return n >= new Date().getFullYear();
}

function generateBio(profile) {
  const studentVoice = isCurrentStudentByGradYear(profile.graduationYear);
  const parts = [];
  parts.push(`Hi, I'm ${profile.firstName || 'there'}.`);

  if (profile.currentJobTitle && profile.currentCompany) {
    const a = indefiniteArticle(profile.currentJobTitle);
    if (studentVoice) {
      parts.push(`I'm currently ${a} ${profile.currentJobTitle} at ${profile.currentCompany}.`);
    } else {
      parts.push(`I currently work as ${a} ${profile.currentJobTitle} at ${profile.currentCompany}.`);
    }
  } else if (profile.currentJobTitle) {
    const a = indefiniteArticle(profile.currentJobTitle);
    if (studentVoice) {
      parts.push(`I'm currently ${a} ${profile.currentJobTitle}.`);
    } else {
      parts.push(`I currently work as ${a} ${profile.currentJobTitle}.`);
    }
  }

  if (profile.pastJobs && profile.pastJobs.length > 0) {
    const { title, company } = profile.pastJobs[0];
    if (title && company) {
      const a = indefiniteArticle(title);
      parts.push(`Previously, I was ${a} ${title} at ${company}.`);
    } else if (company) {
      parts.push(`Previously, I worked at ${company}.`);
    } else if (title) {
      const a = indefiniteArticle(title);
      parts.push(`Previously, I was ${a} ${title}.`);
    }
  }

  const edu = educationLine(profile.almaMater ?? '', profile.graduationYear);
  if (edu) parts.push(edu);

  parts.push(`Let's connect!`);
  return parts.join(' ');
}

function isLikelyAutoGeneratedBio(stored) {
  const t = String(stored ?? '').trim();
  if (!t) return true;
  if (!/^Hi, I'?m /i.test(t)) return false;
  if (/Let's connect!/i.test(t)) return true;
  return /(studied at|studying at|graduated in|will graduate in|currently work as|I'm currently)/i.test(t);
}

function resolveDisplayBio(storedBio, profile) {
  const built = generateBio(profile);
  const stored = String(storedBio ?? '').trim();
  if (!stored || isLikelyAutoGeneratedBio(stored)) return built;
  return stored;
}

function bioProfileFromRow(row, baseUser) {
  const pastCompanies = Array.isArray(row?.past_companies)
    ? row.past_companies
    : Array.isArray(baseUser?.pastCompanies)
      ? baseUser.pastCompanies
      : [];
  const first = pastCompanies[0] ? parsePastCompany(pastCompanies[0]) : { title: '', company: '' };
  const pastJobs =
    first.title || first.company ? [{ title: first.title, company: first.company }] : undefined;
  return {
    firstName: coalesceNonEmpty(row?.first_name, baseUser?.firstName),
    currentJobTitle: coalesceNonEmpty(row?.current_job_title, baseUser?.currentJobTitle),
    currentCompany: coalesceNonEmpty(row?.current_company, baseUser?.currentCompany),
    pastJobs,
    almaMater: coalesceNonEmpty(row?.alma_mater, baseUser?.almaMater),
    graduationYear: normalizeGraduationYear(
      coalesceNonEmpty(row?.graduation_year, baseUser?.graduationYear)
    ),
  };
}

function bioProfileFromUser(user) {
  return bioProfileFromRow(null, user);
}

module.exports = {
  generateBio,
  resolveDisplayBio,
  isLikelyAutoGeneratedBio,
  bioProfileFromRow,
  bioProfileFromUser,
  parseGradYear,
  normalizeGraduationYear,
};
